name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      target-directory:
        type: string
        description: Target directory
        default: "src"

jobs:
  deploy:
    uses: ./.github/workflows/mi-reusable-workflow.yml
    with:
      target-directory: ${{ inputs.target-directory }}

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"
